# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 677f1c5e5c9494524e407676e6e4c424015c69744829de2d6cf383ee02074430e6c8bed6661b0490070d08da2360bfea2ad8e8fca1c3be750833e05b444ec54a

test:
  secret_key_base: 50cdb4f21a0fb7f63df1ac78073d76b69a1e950f25c9dee01a50e077e9f125ee1c3db54e03ffadea150a804034dd412f7eb90692105252f6bff77aea89714f36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
